sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mecab mecab-ipadic-utf8 libmecab-dev -y
language: java
jdk:
  - oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
